# Generated by Django 2.2.5 on 2019-11-11 11:27

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerprofile_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.IntegerField(null=True, validators=[customer.models.phone_number_validation]),
        ),
    ]
